# Normal equations square the condition number; QR does not
import numpy as np

m = 50
x = np.linspace(0, 1, m)
print(" deg   cond(A)     cond(A^T A)   error normal eq.   error QR")
for n in [3, 6, 9, 12, 15]:
    A = np.vander(x, n + 1, increasing=True)
    c_true = np.ones(n + 1)                   # data generated by a known polynomial
    y = A @ c_true
    c_ne = np.linalg.solve(A.T @ A, A.T @ y)  # normal equations
    Q, R = np.linalg.qr(A)                    # reduced QR factorisation
    c_qr = np.linalg.solve(R, Q.T @ y)
    print(f"{n:3d}  {np.linalg.cond(A):10.2e}  {np.linalg.cond(A.T @ A):12.2e}"
          f"  {np.max(np.abs(c_ne - c_true)):14.2e}  {np.max(np.abs(c_qr - c_true)):10.2e}")
